# https://trivy.dev/latest/docs/references/configuration/config-file/
---
scan:
  scanners:
    - vuln
    - misconfig
    - secret
    - license
misconfiguration:
  scanners:
    - dockerfile
ignorefile: .trivyignore.yml
